---
sidebar: sidebar
permalink: reference-new.html
keywords: what's new, new, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.10.0 includes several new features and enhancements.
---

= What's new in Cloud Volumes ONTAP 9.10.0
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP 9.10.0 includes several new features and enhancements.

Additional features and enhancements are also introduced in the latest versions of Cloud Manager. See the https://docs.netapp.com/us-en/occm/reference_new_occm.html[Cloud Manager Release Notes^] for details.

== 9.10.0 GA (4 Oct 2021)

The 9.10.0 GA release is available in AWS, Azure, and Google Cloud. This release includes the following new features and enhancements.

=== Improved write performance

We improved Cloud Volumes ONTAP write performance when high write speed is enabled.

=== Increased NVRAM disk size in Azure

The NVRAM disk size was increased from 128 GiB to 512 GiB for new Cloud Volumes ONTAP systems in Azure.

NOTE: If you choose a single node system and the virtual machine supports Ultra SSDs, then the system uses a 32 GiB Ultra SSD for NVRAM, rather than a 512 GiB Premium SSD.

== Required version of the Cloud Manager Connector

The Cloud Manager Connector must be running version 3.9.11 or later to deploy new Cloud Volumes ONTAP 9.10.0 systems and to upgrade existing systems to 9.10.0.

== Upgrade notes

* Upgrades of Cloud Volumes ONTAP must be completed from Cloud Manager. You should not upgrade Cloud Volumes ONTAP by using System Manager or the CLI. Doing so can impact system stability.

* You can upgrade to Cloud Volumes ONTAP 9.10.0 from the 9.9.1 release and from the 9.9.0 release. Cloud Manager will prompt you to upgrade your existing Cloud Volumes ONTAP 9.9.1 and 9.9.0 systems to the 9.10.0 release.
+
http://docs.netapp.com/us-en/occm/task_updating_ontap_cloud.html#upgrading-cloud-volumes-ontap-from-cloud-manager-notifications[Learn how to upgrade when Cloud Manager notifies you^].

* The upgrade of a single node system takes the system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrading an HA pair is nondisruptive and I/O is uninterrupted. During this nondisruptive upgrade process, each node is upgraded in tandem to continue serving I/O to clients.

=== c4, m4, and r4 instance types

Starting with the 9.8 release, c4, m4, and r4 instance types aren't supported with new Cloud Volumes ONTAP systems. If you have an existing Cloud Volumes ONTAP system that's running on a c4, m4, or r4 instance type, you can still upgrade to this release.

We recommend changing to an instance type in the c5, m5, or r5 instance family.

=== DS3_v2

Starting with the 9.9.1 release, the DS3_v2 VM type is no longer supported with new and existing Cloud Volumes ONTAP systems. If you have an existing system running on this VM type, you'll need to change VM types before you upgrade to 9.10.0.
